window.FPL_CONTACTS = {
  "SKBO": {
    "code": "SKBO",
    "city": "Bogotá",
    "airport": "El Dorado",
    "department": "Bogotá D.C.",
    "regional": "Centro Sur",
    "tower": "3175387792",
    "fpl": "3175171035",
    "email": "SKBOZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Bogotá; El Dorado; SKBO",
    "searchKey": "skbo bogota el dorado bogota d c centro sur bogota el dorado skbo",
    "sourceDate": "2022-06-10"
  },
  "SKGY": {
    "code": "SKGY",
    "city": "Guaymaral",
    "airport": "Flaminio Suárez Camacho",
    "department": "Cundinamarca",
    "regional": "Centro Sur",
    "tower": "3175171117",
    "fpl": "3185863359",
    "email": "SKGYZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Guaymaral; Flaminio Suárez Camacho; SKGY",
    "searchKey": "skgy guaymaral flaminio suarez camacho cundinamarca centro sur guaymaral flaminio suarez camacho skgy",
    "sourceDate": "2022-06-10"
  },
  "SKFL": {
    "code": "SKFL",
    "city": "Florencia",
    "airport": "Gustavo Artunduaga Paredes",
    "department": "Caquetá",
    "regional": "Centro Sur",
    "tower": "3175387822",
    "fpl": "3175171210",
    "email": "SKFLZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Florencia; Gustavo Artunduaga Paredes; SKFL",
    "searchKey": "skfl florencia gustavo artunduaga paredes caqueta centro sur florencia gustavo artunduaga paredes skfl",
    "sourceDate": "2022-06-10"
  },
  "SKGI": {
    "code": "SKGI",
    "city": "Girardot",
    "airport": "Santiago Vila",
    "department": "Cundinamarca",
    "regional": "Centro Sur",
    "tower": "3175171183",
    "fpl": "3176354593",
    "email": "SKGIZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Girardot; Santiago Vila; SKGI",
    "searchKey": "skgi girardot santiago vila cundinamarca centro sur girardot santiago vila skgi",
    "sourceDate": "2022-06-10"
  },
  "SKIB": {
    "code": "SKIB",
    "city": "Ibagué",
    "airport": "Perales",
    "department": "Tolima",
    "regional": "Centro Sur",
    "tower": "3175171114",
    "fpl": "3185479912",
    "email": "SKIBZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Ibagué; Perales; SKIB",
    "searchKey": "skib ibague perales tolima centro sur ibague perales skib",
    "sourceDate": "2022-06-10"
  },
  "SKLT": {
    "code": "SKLT",
    "city": "Leticia",
    "airport": "Alfredo Vásquez Cobo",
    "department": "Amazonas",
    "regional": "Centro Sur",
    "tower": "3175171132",
    "fpl": "3165221144",
    "email": "SKLTZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Leticia; Alfredo Vásquez Cobo; SKLT",
    "searchKey": "sklt leticia alfredo vasquez cobo amazonas centro sur leticia alfredo vasquez cobo sklt",
    "sourceDate": "2022-06-10"
  },
  "SKQU": {
    "code": "SKQU",
    "city": "Mariquita",
    "airport": "José Celestino Mutis",
    "department": "Tolima",
    "regional": "Centro Sur",
    "tower": "3175171094",
    "fpl": "3185165780",
    "email": "SKQUZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Mariquita; José Celestino Mutis; SKQU",
    "searchKey": "skqu mariquita jose celestino mutis tolima centro sur mariquita jose celestino mutis skqu",
    "sourceDate": "2022-06-10"
  },
  "SKNV": {
    "code": "SKNV",
    "city": "Neiva",
    "airport": "Benito Salas",
    "department": "Huila",
    "regional": "Centro Sur",
    "tower": "3175171147",
    "fpl": "3167422604",
    "email": "SKNVZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Neiva; Benito Salas; SKNV",
    "searchKey": "sknv neiva benito salas huila centro sur neiva benito salas sknv",
    "sourceDate": "2022-06-10"
  },
  "SKAS": {
    "code": "SKAS",
    "city": "Puerto Asís",
    "airport": "Tres de Mayo",
    "department": "Putumayo",
    "regional": "Centro Sur",
    "tower": "3175387818",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Puerto Asís; Tres de Mayo; SKAS",
    "searchKey": "skas puerto asis tres de mayo putumayo centro sur puerto asis tres de mayo skas",
    "sourceDate": "2022-06-10"
  },
  "SKBQ": {
    "code": "SKBQ",
    "city": "Barranquilla",
    "airport": "Ernesto Cortissoz",
    "department": "Atlántico",
    "regional": "Norte",
    "tower": "3175171021",
    "fpl": "3175171039",
    "email": "SKBQZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Barranquilla; Ernesto Cortissoz; SKBQ",
    "searchKey": "skbq barranquilla ernesto cortissoz atlantico norte barranquilla ernesto cortissoz skbq",
    "sourceDate": "2022-06-10"
  },
  "SKCG": {
    "code": "SKCG",
    "city": "Cartagena",
    "airport": "Rafael Núñez",
    "department": "Bolívar",
    "regional": "Norte",
    "tower": "3175171095",
    "fpl": "3153413225",
    "email": "SKCGZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Cartagena; Rafael Núñez; SKCG",
    "searchKey": "skcg cartagena rafael nunez bolivar norte cartagena rafael nunez skcg",
    "sourceDate": "2022-06-10"
  },
  "SKSP": {
    "code": "SKSP",
    "city": "San Andrés",
    "airport": "Gustavo Rojas Pinilla",
    "department": "San Andrés y Providencia",
    "regional": "Norte",
    "tower": "3175387834",
    "fpl": "3182064662",
    "email": "SKSPZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "San Andrés; Gustavo Rojas Pinilla; SKSP",
    "searchKey": "sksp san andres gustavo rojas pinilla san andres y providencia norte san andres gustavo rojas pinilla sksp",
    "sourceDate": "2022-06-10"
  },
  "SKSM": {
    "code": "SKSM",
    "city": "Santa Marta",
    "airport": "Simón Bolívar",
    "department": "Magdalena",
    "regional": "Norte",
    "tower": "3175171007",
    "fpl": "3156966455",
    "email": "SKSMZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Santa Marta; Simón Bolívar; SKSM",
    "searchKey": "sksm santa marta simon bolivar magdalena norte santa marta simon bolivar sksm",
    "sourceDate": "2022-06-10"
  },
  "SKVP": {
    "code": "SKVP",
    "city": "Valledupar",
    "airport": "Alfonso López Pumarejo",
    "department": "Cesar",
    "regional": "Norte",
    "tower": "3175171096",
    "fpl": "3156966455",
    "email": "SKVPZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Valledupar; Alfonso López Pumarejo; SKVP",
    "searchKey": "skvp valledupar alfonso lopez pumarejo cesar norte valledupar alfonso lopez pumarejo skvp",
    "sourceDate": "2022-06-10"
  },
  "SKCZ": {
    "code": "SKCZ",
    "city": "Corozal",
    "airport": "Las Brujas",
    "department": "Sucre",
    "regional": "Norte",
    "tower": "3175387835",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Corozal; Las Brujas; SKCZ",
    "searchKey": "skcz corozal las brujas sucre norte corozal las brujas skcz",
    "sourceDate": "2022-06-10"
  },
  "SKPV": {
    "code": "SKPV",
    "city": "Providencia",
    "airport": "El Embrujo",
    "department": "San Andrés y Providencia",
    "regional": "Norte",
    "tower": "3175171214",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Providencia; El Embrujo; SKPV",
    "searchKey": "skpv providencia el embrujo san andres y providencia norte providencia el embrujo skpv",
    "sourceDate": "2022-06-10"
  },
  "SKRH": {
    "code": "SKRH",
    "city": "Riohacha",
    "airport": "Almirante Padilla",
    "department": "La Guajira",
    "regional": "Norte",
    "tower": "3175387837",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Riohacha; Almirante Padilla; SKRH",
    "searchKey": "skrh riohacha almirante padilla la guajira norte riohacha almirante padilla skrh",
    "sourceDate": "2022-06-10"
  },
  "SKRG": {
    "code": "SKRG",
    "city": "Rionegro",
    "airport": "José María Córdova",
    "department": "Antioquia",
    "regional": "Noroccidente",
    "tower": "3175171011",
    "fpl": "3176465224",
    "email": "SKRGZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Rionegro; José María Córdova; SKRG",
    "searchKey": "skrg rionegro jose maria cordova antioquia noroccidente rionegro jose maria cordova skrg",
    "sourceDate": "2022-06-10"
  },
  "SKMD": {
    "code": "SKMD",
    "city": "Medellín",
    "airport": "Olaya Herrera",
    "department": "Antioquia",
    "regional": "Noroccidente",
    "tower": "3175171078",
    "fpl": "3106488038",
    "email": "SKMDZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Medellín; Olaya Herrera; SKMD",
    "searchKey": "skmd medellin olaya herrera antioquia noroccidente medellin olaya herrera skmd",
    "sourceDate": "2022-06-10"
  },
  "SKMR": {
    "code": "SKMR",
    "city": "Montería",
    "airport": "Los Garzones",
    "department": "Córdoba",
    "regional": "Noroccidente",
    "tower": "3175171098",
    "fpl": "3188508541",
    "email": "SKMRZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Montería; Los Garzones; SKMR",
    "searchKey": "skmr monteria los garzones cordoba noroccidente monteria los garzones skmr",
    "sourceDate": "2022-06-10"
  },
  "SKUI": {
    "code": "SKUI",
    "city": "Quibdó",
    "airport": "El Caraño",
    "department": "Chocó",
    "regional": "Noroccidente",
    "tower": "3175387807",
    "fpl": "3175177589",
    "email": "SKUIZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Quibdó; El Caraño; SKUI",
    "searchKey": "skui quibdo el carano choco noroccidente quibdo el carano skui",
    "sourceDate": "2022-06-10"
  },
  "SKBS": {
    "code": "SKBS",
    "city": "Bahía Solano",
    "airport": "José Celestino Mutis",
    "department": "Chocó",
    "regional": "Noroccidente",
    "tower": "3128267400",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Bahía Solano; José Celestino Mutis; SKBS",
    "searchKey": "skbs bahia solano jose celestino mutis choco noroccidente bahia solano jose celestino mutis skbs",
    "sourceDate": "2022-06-10"
  },
  "SKLC": {
    "code": "SKLC",
    "city": "Carepa",
    "airport": "Antonio Roldán Betancourt",
    "department": "Antioquia",
    "regional": "Noroccidente",
    "tower": "3158066109",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Carepa; Antonio Roldán Betancourt; SKLC",
    "searchKey": "sklc carepa antonio roldan betancourt antioquia noroccidente carepa antonio roldan betancourt sklc",
    "sourceDate": "2022-06-10"
  },
  "SKMZ": {
    "code": "SKMZ",
    "city": "Manizales",
    "airport": "La Nubia",
    "department": "Caldas",
    "regional": "Noroccidente",
    "tower": "3175171211",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Manizales; La Nubia; SKMZ",
    "searchKey": "skmz manizales la nubia caldas noroccidente manizales la nubia skmz",
    "sourceDate": "2022-06-10"
  },
  "SKCC": {
    "code": "SKCC",
    "city": "Cúcuta",
    "airport": "Camilo Daza",
    "department": "Norte de Santander",
    "regional": "Nororiente",
    "tower": "3175171100",
    "fpl": "3157335754",
    "email": "SKCCZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Cúcuta; Camilo Daza; SKCC",
    "searchKey": "skcc cucuta camilo daza norte de santander nororiente cucuta camilo daza skcc",
    "sourceDate": "2022-06-10"
  },
  "SKBG": {
    "code": "SKBG",
    "city": "Bucaramanga",
    "airport": "Palonegro",
    "department": "Santander",
    "regional": "Nororiente",
    "tower": "3175171013",
    "fpl": "3175171051",
    "email": "SKBGZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Bucaramanga; Palonegro; SKBG",
    "searchKey": "skbg bucaramanga palonegro santander nororiente bucaramanga palonegro skbg",
    "sourceDate": "2022-06-10"
  },
  "SKUC": {
    "code": "SKUC",
    "city": "Arauca",
    "airport": "Santiago Pérez Quiroz",
    "department": "Arauca",
    "regional": "Nororiente",
    "tower": "3175387801",
    "fpl": "3176567229",
    "email": "SKUCZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Arauca; Santiago Pérez Quiroz; SKUC",
    "searchKey": "skuc arauca santiago perez quiroz arauca nororiente arauca santiago perez quiroz skuc",
    "sourceDate": "2022-06-10"
  },
  "SKEJ": {
    "code": "SKEJ",
    "city": "Barrancabermeja",
    "airport": "Yariguíes",
    "department": "Santander",
    "regional": "Nororiente",
    "tower": "3175171120",
    "fpl": "3173638805",
    "email": "SKEJZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Barrancabermeja; Yariguíes; SKEJ",
    "searchKey": "skej barrancabermeja yariguies santander nororiente barrancabermeja yariguies skej",
    "sourceDate": "2022-06-10"
  },
  "SKSA": {
    "code": "SKSA",
    "city": "Saravena",
    "airport": "Los Colonizadores",
    "department": "Arauca",
    "regional": "Nororiente",
    "tower": "3175387802",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Saravena; Los Colonizadores; SKSA",
    "searchKey": "sksa saravena los colonizadores arauca nororiente saravena los colonizadores sksa",
    "sourceDate": "2022-06-10"
  },
  "SKTM": {
    "code": "SKTM",
    "city": "Tame",
    "airport": "Gustavo Vargas",
    "department": "Arauca",
    "regional": "Nororiente",
    "tower": "3175387804",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Tame; Gustavo Vargas; SKTM",
    "searchKey": "sktm tame gustavo vargas arauca nororiente tame gustavo vargas sktm",
    "sourceDate": "2022-06-10"
  },
  "SKVV": {
    "code": "SKVV",
    "city": "Villavicencio",
    "airport": "Vanguardia",
    "department": "Meta",
    "regional": "Oriente",
    "tower": "3175171031",
    "fpl": "3175171049",
    "email": "SKVVZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Villavicencio; Vanguardia; SKVV",
    "searchKey": "skvv villavicencio vanguardia meta oriente villavicencio vanguardia skvv",
    "sourceDate": "2022-06-10"
  },
  "SKYP": {
    "code": "SKYP",
    "city": "Yopal",
    "airport": "El Yopal",
    "department": "Casanare",
    "regional": "Oriente",
    "tower": "3175171165",
    "fpl": "3186084571",
    "email": "SKYPZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Yopal; El Yopal; SKYP",
    "searchKey": "skyp yopal el yopal casanare oriente yopal el yopal skyp",
    "sourceDate": "2022-06-10"
  },
  "SKMU": {
    "code": "SKMU",
    "city": "Mitú",
    "airport": "Fabio Alberto León Bentley",
    "department": "Vaupés",
    "regional": "Oriente",
    "tower": "3175387797",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Mitú; Fabio Alberto León Bentley; SKMU",
    "searchKey": "skmu mitu fabio alberto leon bentley vaupes oriente mitu fabio alberto leon bentley skmu",
    "sourceDate": "2022-06-10"
  },
  "SKPC": {
    "code": "SKPC",
    "city": "Puerto Carreño",
    "airport": "Germán Olano",
    "department": "Vichada",
    "regional": "Oriente",
    "tower": "3175387794",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Puerto Carreño; Germán Olano; SKPC",
    "searchKey": "skpc puerto carreno german olano vichada oriente puerto carreno german olano skpc",
    "sourceDate": "2022-06-10"
  },
  "SKSJ": {
    "code": "SKSJ",
    "city": "San José del Guaviare",
    "airport": "Jorge E. González T.",
    "department": "Guaviare",
    "regional": "Oriente",
    "tower": "3175387795",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "San José del Guaviare; Jorge E. González T.; SKSJ",
    "searchKey": "sksj san jose del guaviare jorge e gonzalez t guaviare oriente san jose del guaviare jorge e gonzalez t sksj",
    "sourceDate": "2022-06-10"
  },
  "SKPD": {
    "code": "SKPD",
    "city": "Puerto Inírida",
    "airport": "César Gaviria Trujillo",
    "department": "Guainía",
    "regional": "Oriente",
    "tower": "3175171075",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Puerto Inírida; César Gaviria Trujillo; SKPD",
    "searchKey": "skpd puerto inirida cesar gaviria trujillo guainia oriente puerto inirida cesar gaviria trujillo skpd",
    "sourceDate": "2022-06-10"
  },
  "SKCL": {
    "code": "SKCL",
    "city": "Cali",
    "airport": "Alfonso Bonilla Aragón",
    "department": "Valle del Cauca",
    "regional": "Occidente",
    "tower": "3175171026",
    "fpl": "3175171047",
    "email": "SKCLZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Cali; Alfonso Bonilla Aragón; SKCL",
    "searchKey": "skcl cali alfonso bonilla aragon valle del cauca occidente cali alfonso bonilla aragon skcl",
    "sourceDate": "2022-06-10"
  },
  "SKPE": {
    "code": "SKPE",
    "city": "Pereira",
    "airport": "Matecaña",
    "department": "Risaralda",
    "regional": "Occidente",
    "tower": "3175171099",
    "fpl": "3183307370",
    "email": "SKPEZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Pereira; Matecaña; SKPE",
    "searchKey": "skpe pereira matecana risaralda occidente pereira matecana skpe",
    "sourceDate": "2022-06-10"
  },
  "SKAR": {
    "code": "SKAR",
    "city": "Armenia",
    "airport": "El Edén",
    "department": "Quindío",
    "regional": "Occidente",
    "tower": "3175171122",
    "fpl": "3175171233",
    "email": "SKARZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Armenia; El Edén; SKAR",
    "searchKey": "skar armenia el eden quindio occidente armenia el eden skar",
    "sourceDate": "2022-06-10"
  },
  "SKGO": {
    "code": "SKGO",
    "city": "Cartago",
    "airport": "Santa Ana",
    "department": "Valle del Cauca",
    "regional": "Occidente",
    "tower": "3175387824",
    "fpl": "3175177587",
    "email": "SKGOZPZX@AEROCIVIL.GOV.CO",
    "status": "Completo en fuente",
    "aliases": "Cartago; Santa Ana; SKGO",
    "searchKey": "skgo cartago santa ana valle del cauca occidente cartago santa ana skgo",
    "sourceDate": "2022-06-10"
  },
  "SKPS": {
    "code": "SKPS",
    "city": "Pasto",
    "airport": "Antonio Nariño",
    "department": "Nariño",
    "regional": "Occidente",
    "tower": "3175171118",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Pasto; Antonio Nariño; SKPS",
    "searchKey": "skps pasto antonio narino narino occidente pasto antonio narino skps",
    "sourceDate": "2022-06-10"
  },
  "SKPP": {
    "code": "SKPP",
    "city": "Popayán",
    "airport": "Guillermo León Valencia",
    "department": "Cauca",
    "regional": "Occidente",
    "tower": "3175171123",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Popayán; Guillermo León Valencia; SKPP",
    "searchKey": "skpp popayan guillermo leon valencia cauca occidente popayan guillermo leon valencia skpp",
    "sourceDate": "2022-06-10"
  },
  "SKBU": {
    "code": "SKBU",
    "city": "Buenaventura",
    "airport": "Gerardo Tobar López",
    "department": "Valle del Cauca",
    "regional": "Occidente",
    "tower": "3175387826",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Buenaventura; Gerardo Tobar López; SKBU",
    "searchKey": "skbu buenaventura gerardo tobar lopez valle del cauca occidente buenaventura gerardo tobar lopez skbu",
    "sourceDate": "2022-06-10"
  },
  "SKGP": {
    "code": "SKGP",
    "city": "Guapi",
    "airport": "Juan Casiano",
    "department": "Cauca",
    "regional": "Occidente",
    "tower": "3175387832",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Guapi; Juan Casiano; SKGP",
    "searchKey": "skgp guapi juan casiano cauca occidente guapi juan casiano skgp",
    "sourceDate": "2022-06-10"
  },
  "SKIP": {
    "code": "SKIP",
    "city": "Ipiales",
    "airport": "San Luis",
    "department": "Nariño",
    "regional": "Occidente",
    "tower": "3175387828",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Ipiales; San Luis; SKIP",
    "searchKey": "skip ipiales san luis narino occidente ipiales san luis skip",
    "sourceDate": "2022-06-10"
  },
  "SKCO": {
    "code": "SKCO",
    "city": "Tumaco",
    "airport": "La Florida",
    "department": "Nariño",
    "regional": "Occidente",
    "tower": "3175387830",
    "fpl": "",
    "email": "",
    "status": "Datos parciales; verificar",
    "aliases": "Tumaco; La Florida; SKCO",
    "searchKey": "skco tumaco la florida narino occidente tumaco la florida skco",
    "sourceDate": "2022-06-10"
  }
};
